plugins:
  - uses:
      - plugin: https://ubiquity-os-daemon-pricing-development.ubiquity.workers.dev
        with:
          globalConfigUpdate:
            excludeRepos: []
          labels:
            time:
              - name: "Time: <15 Minutes"
                collaboratorOnly: false
              - name: "Time: <1 Hour"
                collaboratorOnly: false
              - name: "Time: <2 Hours"
                collaboratorOnly: false
              - name: "Time: <4 Hours"
                collaboratorOnly: false
              - name: "Time: <1 Day"
                collaboratorOnly: false
              - name: "Time: <1 Week"
                collaboratorOnly: false
            priority:
              - name: "Priority: 0 (Regression)"
                collaboratorOnly: false
              - name: "Priority: 1 (Normal)"
                collaboratorOnly: false
              - name: "Priority: 2 (Medium)"
                collaboratorOnly: false
              - name: "Priority: 3 (High)"
                collaboratorOnly: false
              - name: "Priority: 4 (Urgent)"
                collaboratorOnly: false
              - name: "Priority: 5 (Emergency)"
                collaboratorOnly: false
          basePriceMultiplier: 1
          shouldFundContributorClosedIssue: false
